### ISSUE TITLE
Any idea how to use the mod?

### ISSUE THREAD

**Issue by ellet0** [oldnapalm/GTACoOp#1]
The `README.md` doesn't provide any instructions on how to use the script/mod in GTA V
Can we use it to play GTA V story missions with other players?
What is the difference between this project and [GtaCoop](https://github.com/GTACoop/GTACoop)

It has the same name and description

**Comment by oldnapalm** [comment]
Added installation instructions to the README.

I don't think you will be able to play story missions with this, although I have not tried it myself.

https://github.com/GTACoop/GTACoop is the original mod. This repository has further development.

**Comment by ellet0** [comment]
> Added installation instructions to the README.
> 
> I don't think you will be able to play story missions with this, although I have not tried it myself.
> 
> https://github.com/GTACoop/GTACoop is the original mod. This repository has further development.

Thank you for the reply.
