### ISSUE TITLE
WaveOutPut error

### ISSUE THREAD

**Issue by ShardSonic** [oldnapalm/GTACoop#11]
I want to play this mod, but I have this error failed to instantiate script GTACOoP.Main constructor threw an exception: NAudio.MmException: BadDeviceld calling waveOutOpen 
![1723822911644820312676229423095](https://github.com/user-attachments/assets/ee440a39-3ae0-4eff-981a-90ca69b5f6fa)

**Comment by oldnapalm** [comment]
Please provide details about your setup. What's the default sound output device?

https://www.majorgeeks.com/content/page/how_to_change_default_sound_output_device_in_windows_10.html

If you don't have speakers or headphones connected, download the version without voice

https://github.com/oldnapalm/GTACoop/releases/download/v0.9.4.7/client-0.9.4.7.zip

**Comment by ShardSonic** [comment]
I have speakers

**Comment by oldnapalm** [comment]
I need more details than that.

**Comment by ShardSonic** [comment]
I fix that just download version without voice
