### ISSUE TITLE
Unable to connect to the created server

### ISSUE THREAD

**Issue by ArashdeepSaini** [oldnapalm/GTACoop#15]
Hi, there's an issue every time with the server that I create on my PC to play with my friends. I am able to join my server and see my server in the server browser in game but friends are not able to see my server on server browser and even if they try to quick connect manually by entering the IP, Port and password, they are unable to connect to it and get error message like this. 
"You have been disconnected: Failed to establish connection - no response from remote host"

Even if my friends create a server, I am not able to join it as well. I get the same error.

We have tried creating new rule in inbound and outbound connections to allow all connections in Advanced settings of firewall for GTAV.exe and gtaserver.core.exe to make sure that there isn't any firewall interference with this issue. I have allowed all apps in my pc for inbound and outbound connections to get it working but nothing seems to work. I did this because I found this thread.
https://forum.gta.world/en/topic/1321-disconnected-no-response-from-remote-host/

I need help please.

**Comment by oldnapalm** [comment]
This situation is explained in the wiki, if clients are not in the same LAN, the server port needs to be forwarded in the router. Alternatively a VPN software like Hamachi can be used.

https://github.com/oldnapalm/GTACoop/wiki/Server#connecting
