### ISSUE TITLE
I receive "Error: Menu not opened yet" when I press F9

### ISSUE THREAD

**Issue by khahdihdz** [oldnapalm/GTACoop#18]
I followed the instructions but I don't understand why I'm not getting any response, nothing happens when I press `F9` in game and inside the `clientSettings.xml` file there is no content.

**Comment by oldnapalm** [comment]
See https://github.com/oldnapalm/GTACoop/wiki/Client#troubleshooting

If it's not the same as #10 and #12, post your logs.
