### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by JoviCuber** [oldnapalm/GTACoop#20]
Hello, i installed your mod, GTA Coop, and it doesn't work. I have cracked version of GTA V, but when i click F9, menu doesn't open, but the menyoo's object spooner key is changed. Please help me with it. Thanks

**Comment by oldnapalm** [comment]
Provide logs, see https://github.com/oldnapalm/GTACoop/wiki/Client#troubleshooting

**Comment by JoviCuber** [comment]
> Provide logs, see https://github.com/oldnapalm/GTACoop/wiki/Client#troubleshooting

Hello, thank you for your reply. I saw the ScriptHookVDotNet's log, and it says that the mod could not be loaded because of an exception(See the attached file).
[ScriptHookVDotNet.log](https://github.com/user-attachments/files/17326687/ScriptHookVDotNet.log)

**Comment by oldnapalm** [comment]
See #10

**Comment by JoviCuber** [comment]
Thank you for your reply, I did what was written in that post and it worked! Thank you for your help!
