### ISSUE TITLE
Friend can't see my server

### ISSUE THREAD

**Issue by GrishaKosak** [oldnapalm/GTACoop#21]
Hello,

 I did everything as it should. The mod works, I set up a server, but my friend doesn't see it. I have unblocked ports: (30120-30120, 4499-4499, 6672-6672, 61455-61458) and antiviruses are disabled.

**Comment by oldnapalm** [comment]
Only the port configured in serverSettings.xml (default 4499) needs to be exposed, and the protocol must be UDP. If it's [forwarded in the router](https://github.com/oldnapalm/GTACoop/wiki/Server#port-forwarding) and [allowed in firewall](https://github.com/oldnapalm/GTACoop/wiki/Server#add-windows-firewall-rule) but it still doesn't work, maybe your internet provider doesn't allow port forwarding. Alternatively you can use a VPN like [Hamachi](https://github.com/oldnapalm/GTACoop/wiki/Server#hamachi).
