### ISSUE TITLE
Request for gtaserver.core.dll file

### ISSUE THREAD

**Issue by Darshanjk** [oldnapalm/GTACoop#22]
HI i am using GTACoop Server and i want to develop a plugin so kindly give me gtaserver.core.dll i can't find it any where and i can't build it so please give me the file.

**Comment by oldnapalm** [comment]
`gtaserver.core.dll` will be created in `gtaserver.core\bin\Debug\net6.0` when you build GTACoop. If you are going to develop a plugin I suppose you can build the server as well.
