### ISSUE TITLE
Error in Package

### ISSUE THREAD

**Issue by Darshan-JKD1** [oldnapalm/GTACoop#24]
![image_2024-12-14_105049569](https://github.com/user-attachments/assets/16cf53bf-79f7-4a50-bdd7-24e84a054e85)
Please help me to solve this error

**Comment by oldnapalm** [comment]
Add https://gitlab.com/api/v4/projects/20574571/packages/nuget/index.json to NuGet package sources.

https://learn.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio#package-sources
