### ISSUE TITLE
Fix for error

### ISSUE THREAD

**Issue by Darshan-jk** [oldnapalm/GTACoop#27]
![code](https://github.com/user-attachments/assets/86b9f608-56a6-459a-b799-8d514208c1bd)
Bro how to fix this error.i want to build gtaserver.core.dll file.

**Comment by oldnapalm** [comment]
Please stop opening new issues with the same question.

**Comment by Darshan-JKD1** [comment]
Ok bro

**Comment by Darshanjk** [comment]
Can you please send gtaserver.core.dll please.

Mail id : darshanvj21@gmail.com 
It may be very helpfull please bro

**Comment by oldnapalm** [comment]
https://github.com/oldnapalm/GTACoop/issues/26#issuecomment-2543071391

**Comment by Darshan-jk** [comment]
![code](https://github.com/user-attachments/assets/1f454a7d-4765-4173-b1ed-f87cf16c73a1)
Please tell me how to solve this error.

**Comment by oldnapalm** [comment]
If you did this https://github.com/oldnapalm/GTACoop/issues/24#issuecomment-2543051665 and installed the package Lidgren.Network.MultiTarget, I have no idea.

**Comment by Darshan-jk** [comment]
Mail id : darshanvj21@gmail.com please send the file bro please.......it will be more helpfull please......

**Comment by oldnapalm** [comment]
I won't send it, you can stop asking, it won't be helpful. You need to be able to build the server if you want to build a plugin later.

**Comment by Darshan-jk** [comment]
ok bro

**Comment by Darshan-jk** [comment]
Thanks Bro I have Successfully Build it.

**Comment by oldnapalm** [comment]
https://github.com/oldnapalm/GTACoop/wiki/Development is updated with Lidgren.Network.MultiTarget NuGet package source.

**Comment by Darshanjk** [comment]
Bro ,How can i build server for linux in windows.

**Comment by oldnapalm** [comment]
Google is your friend

https://learn.microsoft.com/pt-br/dotnet/core/tools/dotnet-build#examples

You don't plan to ask how to perform every step here, do you? "Issues" is not a help desk.
