### ISSUE TITLE
Help me Plugins

### ISSUE THREAD

**Issue by Smaill339** [oldnapalm/GTACoop#7]
Hello, I have a problem, I hope you will help, when I installed the plugin, I got an error in the console and it says to send you a file translated by a translator (Problem a minidump has been written to C:\Users\Name\OneDrive\desctop\Server\crashes\ please send this file to the developers)
![photo_5194967668879386742_y](https://github.com/oldnapalm/GTACoop/assets/174369727/81d128df-ef32-424a-a4dd-0fa52ec1be75)

**Comment by oldnapalm** [comment]
Have you put the file NoNPC.dll in the Plugins folder?

You can find it in https://github.com/oldnapalm/GTACoop/releases/download/discord_bot_0.1/DiscordBot.zip

**Comment by Smaill339** [comment]
okay server starting but NPC dont delete

**Comment by Smaill339** [comment]
okay server starting but NPC dont delete
![photo_5195463449839263320_w](https://github.com/oldnapalm/GTACoop/assets/174369727/99406012-d004-47c2-a361-3f004e521a8b)

**Comment by oldnapalm** [comment]
It only disables shared NPCs (from other players). To disable your local NPCs just check "disable traffic/peds" in settings menu.

**Comment by Smaill339** [comment]
how to pretend to be an administrator

**Comment by oldnapalm** [comment]
Use setgroup command in server console (player must be already registered in game chat, set admin group)

```
setgroup
INFO [GameServer] Usage: setgroup <player> <group>
```

**Comment by Smaill339** [comment]
yes for plugins

**Comment by oldnapalm** [comment]
I only wrote Discord bridge and Race (both in releases page).

I don't think other plugins for GTA Coop exist.

**Comment by Smaill339** [comment]
ok thank you and can i ban users?

**Comment by Smaill339** [comment]
And also how can I add my server to the browser in the game because I also made the default port 4499 but I use playit.gg to open the port is there any way I can fix it,

**Comment by oldnapalm** [comment]
I believe it's not possible to ban users.

To add server to browser you need to expose the port 4499 UDP to the internet, see https://github.com/oldnapalm/GTACoop/wiki/Server#port-forwarding

**Comment by Smaill339** [comment]
how come his server is displayed in the browser and my server is not
![photo_5197715249652948950_x](https://github.com/oldnapalm/GTACoop/assets/174369727/3b669854-311e-4847-8843-1280f5e309ac)

**Comment by oldnapalm** [comment]
The port number does not matter (can be any number), what matters is that it's exposed to the internet (port forwarding configured in the router).

**Comment by Smaill339** [comment]
how can I do it so that the server is displayed, people can enter, but the server itself is not displayed, why is it so?

**Comment by oldnapalm** [comment]
That's how the master server works, it considers the IP address from which it receives the announcing message. When you use double-p.gl.at.ply.gg the master server does not know about that host, it only knows the real IP address of your server, and the server browser will only display it if it's reachable.

**Comment by Smaill339** [comment]
and how should I make him understand this IP?

**Comment by oldnapalm** [comment]
It's not possible, the master server only uses the IP from the announce request, you can't specify a different IP manually.

Like I said earlier, the only way is through port forwarding.

**Comment by Smaill339** [comment]
it's sad, but I can't do the redirection, I have a dominic IP, it changes every time after restarting the server, everything is great, thank you

**Comment by oldnapalm** [comment]
It does not matter if your public IP is dynamic, if you configure port forwarding (WAN -> LAN IP, protocol UDP) it should work, every time your public IP changes, it will be updated on master server.

If it's your LAN IP which is dynamic, you can resolve with address reservation to MAC in router's DHCP settings (although this is very unusual, normally the LAN IP stays the same for a long time).

**Comment by Smaill339** [comment]
I still didn't understand, I did everything with the ports, but it doesn't work like that

**Comment by oldnapalm** [comment]
Maybe your internet provider does not allow port forwarding, or you have a more complex network setup (the router you are configuring is behind another firewall which blocks all incoming connections).

**Comment by Smaill339** [comment]
maybe okay thank you good luck man!

**Comment by Sriharan-S** [comment]
anyone help how can i setup Race mode

**Comment by oldnapalm** [comment]
> anyone help how can i setup Race mode

You can find instructions here https://github.com/oldnapalm/GTACoop/releases/tag/race_gamemode_0.1
